######################################################################
# Automatically generated by qmake (2.01a) mar. avr. 14 19:30:45 2015
######################################################################

CONFIG += c++11

QT += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = interpretor
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += interpretor.h packet.h modelChator.h
SOURCES += interpretor.cpp main.cpp
